name: GraalVM Linux
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm-community'
          github-token:
            ${{ secrets.GITHUB_TOKEN }}
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev  build-essential zlib1g-dev libstdc++-10-dev
      - name: Make staging directory
        run: mkdir staging
      - name: Gluon Build
        run: ./mvnw -ntp -Pdesktop gluonfx:build gluonfx:package
      - name: Copy native image to staging
        run: |
          set -e
          chmod +x target/gluonfx/x86_64-linux/swaggerific
          tar -czvf staging/swaggerific_x86.tar.gz -C target/gluonfx/x86_64-linux swaggerific
          cp -r target/gluonfx/x86_64-linux/*.tar.gz staging

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_linux"
          prerelease: true
          title: "Linux Development Build"
          files: |
            staging/*
        id: "automatic_releases"
