name: Send Bluesky Post

on:
  workflow_run:
    workflows: [ "GraalVM Windows", "GraalVM Linux", "macOS" ]
    types:
      - completed
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    #    this line makes sure that the post is only sent when the macOS build is successful, meaning only one post
    if: ${{ github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow.name == 'macOS') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Latest Release and Commits
        id: get_info
        run: |
          # Get tag info
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
          else
            echo "tag=No tags found" >> "$GITHUB_OUTPUT"
          fi

          # Get commit info with proper delimiter handling
          echo "commits<<EOF" >> "$GITHUB_OUTPUT"
          git log -3 --pretty=format:"• %s" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"  # Add newline before EOF
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Set Message Content
        id: message
        run: |
          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "🚀 New release(${{ steps.get_info.outputs.tag }})

          Latest changes:
          ${{ steps.get_info.outputs.commits }}

          Download: https://github.com/ozkanpakdil/swaggerific/releases" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Send Bluesky Post
        uses: myConsciousness/bluesky-post@v5
        with:
          text: ${{ steps.message.outputs.content }}
          link-preview-url: "https://github.com/ozkanpakdil/swaggerific"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Send toot to Mastodon
        id: mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          url: ${{ secrets.MASTODON_URL }}
          message: ${{ steps.message.outputs.content }}
